insert into languages(name, native_name, locale, is_active, created_at)
values
    ('Abkhaz', 'аҧсуа' ,'ab', true, current_timestamp),
    ('Afar', 'Afaraf', 'aa', true, current_timestamp),
    ('Afrikaans', 'Afrikaans', 'af', true, current_timestamp),
    ('Akan', 'Akan', 'ak', true, current_timestamp),
    ('Albanian', 'Shqip', 'sq', true, current_timestamp),
    ('Amharic', 'አማርኛ', 'am', true, current_timestamp),
    ('Arabic', 'العربية', 'ar', true, current_timestamp),
    ('Aragonese', 'Aragonés', 'an', true, current_timestamp),
    ('Armenian', 'Հայերեն', 'hy', true, current_timestamp),
    ('Assamese', 'অসমীয়া', 'as', true, current_timestamp),
    ('Avaric', 'авар мацӀ, магӀарул мацӀ', 'av', true, current_timestamp),
    ('Avestan', 'avesta', 'ae', true, current_timestamp),
    ('Aymara', 'aymar aru', 'ay', true, current_timestamp),
    ('Azerbaijani', 'azərbaycan dili', 'az', true, current_timestamp),
    ('Bambara', 'bamanankan', 'bm', true, current_timestamp),
    ('Bashkir', 'башҡорт теле', 'ba', true, current_timestamp),
    ('Basque', 'euskara, euskera', 'eu', true, current_timestamp),
    ('Belarusian', 'Беларуская', 'be', true, current_timestamp),
    ('Bengali', 'বাংলা', 'bn', true, current_timestamp),
    ('Bihari', 'भोजपुरी', 'bh', true, current_timestamp),
    ('Bislama', 'Bislama', 'bi', true, current_timestamp),
    ('Bosnian', 'bosanski jezik', 'bs', true, current_timestamp),
    ('Breton', 'brezhoneg', 'br', true, current_timestamp),
    ('Bulgarian', 'български език', 'bg', true, current_timestamp),
    ('Burmese', 'ဗမာစာ', 'my', true, current_timestamp),
    ('Catalan; Valencian', 'Català', 'ca', true, current_timestamp),
    ('Chamorro', 'Chamoru', 'ch', true, current_timestamp),
    ('Chechen', 'нохчийн мотт', 'ce', true, current_timestamp),
    ('Chichewa; Chewa; Nyanja', 'chiCheŵa, chinyanja', 'ny', true, current_timestamp),
    ('Chinese', '中文 (Zhōngwén), 汉语, 漢語', 'zh', true, current_timestamp),
    ('Chuvash', 'чӑваш чӗлхи', 'cv', true, current_timestamp),
    ('Cornish', 'Kernewek', 'kw', true, current_timestamp),
    ('Corsican', 'corsu, lingua corsa', 'co', true, current_timestamp),
    ('Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'cr', true, current_timestamp),
    ('Croatian', 'hrvatski', 'hr', true, current_timestamp),
    ('Czech', 'česky, čeština', 'cs', true, current_timestamp),
    ('Danish', 'dansk', 'da', true, current_timestamp),
    ('Divehi; Dhivehi; Maldivian;', 'ދިވެހި', 'dv', true, current_timestamp),
    ('Dutch', 'Nederlands, Vlaams', 'nl', true, current_timestamp),
    ('English', 'English', 'en', true, current_timestamp),
    ('Esperanto', 'Esperanto', 'eo', true, current_timestamp),
    ('Estonian', 'eesti, eesti keel', 'et', true, current_timestamp),
    ('Ewe', 'Eʋegbe', 'ee', true, current_timestamp),
    ('Faroese', 'føroyskt', 'fo', true, current_timestamp),
    ('Fijian', 'vosa Vakaviti', 'fj', true, current_timestamp),
    ('Finnish', 'suomi, suomen kieli', 'fi', true, current_timestamp),
    ('French', 'français, langue française', 'fr', true, current_timestamp),
    ('Fula; Fulah; Pulaar; Pular', 'Fulfulde, Pulaar, Pular', 'ff', true, current_timestamp),
    ('Galician', 'Galego', 'gl', true, current_timestamp),
    ('Georgian', 'ქართული', 'ka', true, current_timestamp),
    ('German', 'Deutsch', 'de', true, current_timestamp),
    ('Greek, Modern', 'Ελληνικά', 'el', true, current_timestamp),
    ('Guaraní', 'Avañeẽ', 'gn', true, current_timestamp),
    ('Gujarati', 'ગુજરાતી', 'gu', true, current_timestamp),
    ('Haitian; Haitian Creole', 'Kreyòl ayisyen', 'ht', true, current_timestamp),
    ('Hausa', 'Hausa, هَوُسَ', 'ha', true, current_timestamp),
    ('Hebrew (modern)', 'עברית', 'he', true, current_timestamp),
    ('Herero', 'Otjiherero', 'hz', true, current_timestamp),
    ('Hindi', 'हिन्दी, हिंदी', 'hi', true, current_timestamp),
    ('Hiri Motu', 'Hiri Motu', 'ho', true, current_timestamp),
    ('Hungarian', 'Magyar', 'hu', true, current_timestamp),
    ('Interlingua', 'Interlingua', 'ia', true, current_timestamp),
    ('Indonesian', 'Bahasa Indonesia', 'id', true, current_timestamp),
    ('Interlingue', 'Originally called Occidental; then Interlingue after WWII', 'ie', true, current_timestamp),
    ('Irish', 'Gaeilge', 'ga', true, current_timestamp),
    ('Igbo', 'Asụsụ Igbo', 'ig', true, current_timestamp),
    ('Inupiaq', 'Iñupiaq, Iñupiatun', 'ik', true, current_timestamp),
    ('Ido', 'Ido', 'io', true, current_timestamp),
    ('Icelandic', 'Íslenska', 'is', true, current_timestamp),
    ('Italian', 'Italiano', 'it', true, current_timestamp),
    ('Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'iu', true, current_timestamp),
    ('Japanese', '日本語 (にほんご／にっぽんご)', 'ja', true, current_timestamp),
    ('Javanese', 'basa Jawa', 'jv', true, current_timestamp),
    ('Kalaallisut, Greenlandic', 'kalaallisut, kalaallit oqaasii', 'kl', true, current_timestamp),
    ('Kannada', 'ಕನ್ನಡ', 'kn', true, current_timestamp),
    ('Kanuri', 'Kanuri', 'kr', true, current_timestamp),
    ('Kashmiri', 'कश्मीरी, كشميري‎', 'ks', true, current_timestamp),
    ('Kazakh', 'Қазақ тілі', 'kk', true, current_timestamp),
    ('Khmer', 'ភាសាខ្មែរ', 'km', true, current_timestamp),
    ('Kikuyu, Gikuyu', 'Gĩkũyũ', 'ki', true, current_timestamp),
    ('Kinyarwanda', 'Ikinyarwanda', 'rw', true, current_timestamp),
    ('Kirghiz, Kyrgyz', 'кыргыз тили', 'ky', true, current_timestamp),
    ('Komi', 'коми кыв', 'kv', true, current_timestamp),
    ('Kongo', 'KiKongo', 'kg', true, current_timestamp),
    ('Korean', '한국어 (韓國語), 조선말 (朝鮮語)', 'ko', true, current_timestamp),
    ('Kurdish', 'Kurdî, كوردی‎', 'ku', true, current_timestamp),
    ('Kwanyama, Kuanyama', 'Kuanyama', 'kj', true, current_timestamp),
    ('Latin', 'latine, lingua latina', 'la', true, current_timestamp),
    ('Luxembourgish, Letzeburgesch', 'Lëtzebuergesch', 'lb', true, current_timestamp),
    ('Luganda', 'Luganda', 'lg', true, current_timestamp),
    ('Limburgish, Limburgan, Limburger', 'Limburgs', 'li', true, current_timestamp),
    ('Lingala', 'Lingála', 'ln', true, current_timestamp),
    ('Lao', 'ພາສາລາວ', 'lo', true, current_timestamp),
    ('Lithuanian', 'lietuvių kalba', 'lt', true, current_timestamp),
    ('Luba-Katanga', '', 'lu', true, current_timestamp),
    ('Latvian', 'latviešu valoda', 'lv', true, current_timestamp),
    ('Manx', 'Gaelg, Gailck', 'gv', true, current_timestamp),
    ('Macedonian', 'македонски јазик', 'mk', true, current_timestamp),
    ('Malagasy', 'Malagasy fiteny', 'mg', true, current_timestamp),
    ('Malay', 'bahasa Melayu, بهاس ملايو‎', 'ms', true, current_timestamp),
    ('Malayalam', 'മലയാളം', 'ml', true, current_timestamp),
    ('Maltese', 'Malti', 'mt', true, current_timestamp),
    ('Māori', 'te reo Māori', 'mi', true, current_timestamp),
    ('Marathi (Marāṭhī)', 'मराठी', 'mr', true, current_timestamp),
    ('Marshallese', 'Kajin M̧ajeļ', 'mh', true, current_timestamp),
    ('Mongolian', 'монгол', 'mn', true, current_timestamp),
    ('Nauru', 'Ekakairũ Naoero', 'na', true, current_timestamp),
    ('Navajo, Navaho', 'Diné bizaad, Dinékʼehǰí', 'nv', true, current_timestamp),
    ('Norwegian Bokmål', 'Norsk bokmål', 'nb', true, current_timestamp),
    ('North Ndebele', 'isiNdebele', 'nd', true, current_timestamp),
    ('Nepali', 'नेपाली', 'ne', true, current_timestamp),
    ('Ndonga', 'Owambo', 'ng', true, current_timestamp),
    ('Norwegian Nynorsk', 'Norsk nynorsk', 'nn', true, current_timestamp),
    ('Norwegian', 'Norsk', 'no', true, current_timestamp),
    ('Nuosu', 'ꆈꌠ꒿ Nuosuhxop', 'ii', true, current_timestamp),
    ('South Ndebele', 'isiNdebele', 'nr', true, current_timestamp),
    ('Occitan', 'Occitan', 'oc', true, current_timestamp),
    ('Ojibwe, Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'oj', true, current_timestamp),
    ('Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', 'ѩзыкъ словѣньскъ', 'cu', true, current_timestamp),
    ('Oromo', 'Afaan Oromoo', 'om', true, current_timestamp),
    ('Oriya', 'ଓଡ଼ିଆ', 'or', true, current_timestamp),
    ('Ossetian, Ossetic', 'ирон æвзаг', 'os', true, current_timestamp),
    ('Panjabi, Punjabi', 'ਪੰਜਾਬੀ, پنجابی‎', 'pa', true, current_timestamp),
    ('Pāli', 'पाऴि', 'pi', true, current_timestamp),
    ('Persian', 'فارسی', 'fa', true, current_timestamp),
    ('Polish', 'polski', 'pl', true, current_timestamp),
    ('Pashto, Pushto', 'پښتو', 'ps', true, current_timestamp),
    ('Portuguese', 'Português', 'pt', true, current_timestamp),
    ('Quechua', 'Runa Simi, Kichwa', 'qu', true, current_timestamp),
    ('Romansh', 'rumantsch grischun', 'rm', true, current_timestamp),
    ('Kirundi', 'kiRundi', 'rn', true, current_timestamp),
    ('Romanian, Moldavian, Moldovan', 'română', 'ro', true, current_timestamp),
    ('Russian', 'русский язык', 'ru', true, current_timestamp),
    ('Sanskrit (Saṁskṛta)', 'संस्कृतम्', 'sa', true, current_timestamp),
    ('Sardinian', 'sardu', 'sc', true, current_timestamp),
    ('Sindhi', 'सिन्धी, سنڌي، سندھی‎', 'sd', true, current_timestamp),
    ('Northern Sami', 'Davvisámegiella', 'se', true, current_timestamp),
    ('Samoan', 'gagana faa Samoa', 'sm', true, current_timestamp),
    ('Sango', 'yângâ tî sängö', 'sg', true, current_timestamp),
    ('Serbian', 'српски језик', 'sr', true, current_timestamp),
    ('Scottish Gaelic; Gaelic', 'Gàidhlig', 'gd', true, current_timestamp),
    ('Shona', 'chiShona', 'sn', true, current_timestamp),
    ('Sinhala, Sinhalese', 'සිංහල', 'si', true, current_timestamp),
    ('Slovak', 'slovenčina', 'sk', true, current_timestamp),
    ('Slovene', 'slovenščina', 'sl', true, current_timestamp),
    ('Somali', 'Soomaaliga, af Soomaali', 'so', true, current_timestamp),
    ('Southern Sotho', 'Sesotho', 'st', true, current_timestamp),
    ('Spanish; Castilian', 'español, castellano', 'es', true, current_timestamp),
    ('Sundanese', 'Basa Sunda', 'su', true, current_timestamp),
    ('Swahili', 'Kiswahili', 'sw', true, current_timestamp),
    ('Swati', 'SiSwati', 'ss', true, current_timestamp),
    ('Swedish', 'svenska', 'sv', true, current_timestamp),
    ('Tamil', 'தமிழ்', 'ta', true, current_timestamp),
    ('Telugu', 'తెలుగు', 'te', true, current_timestamp),
    ('Tajik', 'тоҷикӣ, toğikī, تاجیکی‎', 'tg', true, current_timestamp),
    ('Thai', 'ไทย', 'th', true, current_timestamp),
    ('Tigrinya', 'ትግርኛ', 'ti', true, current_timestamp),
    ('Tibetan Standard, Tibetan, Central', 'བོད་ཡིག', 'bo', true, current_timestamp),
    ('Turkmen', 'Türkmen, Түркмен', 'tk', true, current_timestamp),
    ('Tagalog', 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔', 'tl', true, current_timestamp),
    ('Tswana', 'Setswana', 'tn', true, current_timestamp),
    ('Tonga (Tonga Islands)', 'faka Tonga', 'to', true, current_timestamp),
    ('Turkish', 'Türkçe', 'tr', true, current_timestamp),
    ('Tsonga', 'Xitsonga', 'ts', true, current_timestamp),
    ('Tatar', 'татарча, tatarça, تاتارچا‎', 'tt', true, current_timestamp),
    ('Twi', 'Twi', 'tw', true, current_timestamp),
    ('Tahitian', 'Reo Tahiti', 'ty', true, current_timestamp),
    ('Uighur, Uyghur', 'Uyƣurqə, ئۇيغۇرچە‎', 'ug', true, current_timestamp),
    ('Ukrainian', 'українська', 'uk', true, current_timestamp),
    ('Urdu', 'اردو', 'ur', true, current_timestamp),
    ('Uzbek', 'zbek, Ўзбек, أۇزبېك‎', 'uz', true, current_timestamp),
    ('Venda', 'Tshivenḓa', 've', true, current_timestamp),
    ('Vietnamese', 'Tiếng Việt', 'vi', true, current_timestamp),
    ('Volapük', 'Volapük', 'vo', true, current_timestamp),
    ('Walloon', 'Walon', 'wa', true, current_timestamp),
    ('Welsh', 'Cymraeg', 'cy', true, current_timestamp),
    ('Wolof', 'Wollof', 'wo', true, current_timestamp),
    ('Western Frisian', 'Frysk', 'fy', true, current_timestamp),
    ('Xhosa', 'isiXhosa', 'xh', true, current_timestamp),
    ('Yiddish', 'ייִדיש', 'yi', true, current_timestamp),
    ('Yoruba', 'Yorùbá', 'yo', true, current_timestamp),
    ('Zhuang, Chuang', 'Saɯ cueŋƅ, Saw cuengh', 'za', true, current_timestamp)
on conflict (locale)
do update set
    name = excluded.name,
    native_name = excluded.native_name,
    is_active = excluded.is_active;
